// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

package main

import (
	"go.opentelemetry.io/collector/connector"
	forwardconnector "go.opentelemetry.io/collector/connector/forwardconnector"
	"go.opentelemetry.io/collector/exporter"
	debugexporter "go.opentelemetry.io/collector/exporter/debugexporter"
	nopexporter "go.opentelemetry.io/collector/exporter/nopexporter"
	otlpexporter "go.opentelemetry.io/collector/exporter/otlpexporter"
	otlphttpexporter "go.opentelemetry.io/collector/exporter/otlphttpexporter"
	"go.opentelemetry.io/collector/extension"
	ballastextension "go.opentelemetry.io/collector/extension/ballastextension"
	zpagesextension "go.opentelemetry.io/collector/extension/zpagesextension"
	"go.opentelemetry.io/collector/otelcol"
	"go.opentelemetry.io/collector/processor"
	batchprocessor "go.opentelemetry.io/collector/processor/batchprocessor"
	memorylimiterprocessor "go.opentelemetry.io/collector/processor/memorylimiterprocessor"
	"go.opentelemetry.io/collector/receiver"
	nopreceiver "go.opentelemetry.io/collector/receiver/nopreceiver"
	otlpreceiver "go.opentelemetry.io/collector/receiver/otlpreceiver"

	countconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/countconnector"
	datadogconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/datadogconnector"
	exceptionsconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/exceptionsconnector"
	grafanacloudconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/grafanacloudconnector"
	routingconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/routingconnector"
	servicegraphconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/servicegraphconnector"
	spanmetricsconnector "github.com/jacktomcat/opentelemetry-collector-contrib/connector/spanmetricsconnector"
	alertmanagerexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/alertmanagerexporter"
	alibabacloudlogserviceexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/alibabacloudlogserviceexporter"
	awscloudwatchlogsexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/awscloudwatchlogsexporter"
	awsemfexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/awsemfexporter"
	awskinesisexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/awskinesisexporter"
	awss3exporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/awss3exporter"
	awsxrayexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/awsxrayexporter"
	azuredataexplorerexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter"
	azuremonitorexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/azuremonitorexporter"
	carbonexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/carbonexporter"
	cassandraexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/cassandraexporter"
	clickhouseexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/clickhouseexporter"
	coralogixexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/coralogixexporter"
	datadogexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/datadogexporter"
	datasetexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/datasetexporter"
	dynatraceexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/dynatraceexporter"
	elasticsearchexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/elasticsearchexporter"
	fileexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/fileexporter"
	googlecloudexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/googlecloudexporter"
	googlecloudpubsubexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/googlecloudpubsubexporter"
	googlemanagedprometheusexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/googlemanagedprometheusexporter"
	honeycombmarkerexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/honeycombmarkerexporter"
	influxdbexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/influxdbexporter"
	instanaexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/instanaexporter"
	kafkaexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/kafkaexporter"
	loadbalancingexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/loadbalancingexporter"
	logicmonitorexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/logicmonitorexporter"
	logzioexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/logzioexporter"
	lokiexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/lokiexporter"
	mezmoexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/mezmoexporter"
	opencensusexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/opencensusexporter"
	opensearchexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/opensearchexporter"
	prometheusexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/prometheusexporter"
	prometheusremotewriteexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter"
	pulsarexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/pulsarexporter"
	sapmexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/sapmexporter"
	sentryexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/sentryexporter"
	signalfxexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/signalfxexporter"
	skywalkingexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/skywalkingexporter"
	splunkhecexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/splunkhecexporter"
	sumologicexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/sumologicexporter"
	syslogexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/syslogexporter"
	tencentcloudlogserviceexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/tencentcloudlogserviceexporter"
	zipkinexporter "github.com/jacktomcat/opentelemetry-collector-contrib/exporter/zipkinexporter"
	asapauthextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/asapauthextension"
	awsproxy "github.com/jacktomcat/opentelemetry-collector-contrib/extension/awsproxy"
	basicauthextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/basicauthextension"
	bearertokenauthextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/bearertokenauthextension"
	jaegerencodingextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/encoding/jaegerencodingextension"
	jsonlogencodingextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/encoding/jsonlogencodingextension"
	otlpencodingextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/encoding/otlpencodingextension"
	textencodingextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/encoding/textencodingextension"
	zipkinencodingextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/encoding/zipkinencodingextension"
	headerssetterextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/headerssetterextension"
	healthcheckextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/healthcheckextension"
	httpforwarderextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/httpforwarderextension"
	jaegerremotesampling "github.com/jacktomcat/opentelemetry-collector-contrib/extension/jaegerremotesampling"
	oauth2clientauthextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/oauth2clientauthextension"
	dockerobserver "github.com/jacktomcat/opentelemetry-collector-contrib/extension/observer/dockerobserver"
	ecsobserver "github.com/jacktomcat/opentelemetry-collector-contrib/extension/observer/ecsobserver"
	ecstaskobserver "github.com/jacktomcat/opentelemetry-collector-contrib/extension/observer/ecstaskobserver"
	hostobserver "github.com/jacktomcat/opentelemetry-collector-contrib/extension/observer/hostobserver"
	k8sobserver "github.com/jacktomcat/opentelemetry-collector-contrib/extension/observer/k8sobserver"
	oidcauthextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/oidcauthextension"
	opampextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/opampextension"
	pprofextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/pprofextension"
	remotetapextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/remotetapextension"
	sigv4authextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/sigv4authextension"
	solarwindsapmsettingsextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/solarwindsapmsettingsextension"
	dbstorage "github.com/jacktomcat/opentelemetry-collector-contrib/extension/storage/dbstorage"
	filestorage "github.com/jacktomcat/opentelemetry-collector-contrib/extension/storage/filestorage"
	sumologicextension "github.com/jacktomcat/opentelemetry-collector-contrib/extension/sumologicextension"
	attributesprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/attributesprocessor"
	cumulativetodeltaprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor"
	deltatorateprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/deltatorateprocessor"
	filterprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/filterprocessor"
	groupbyattrsprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/groupbyattrsprocessor"
	groupbytraceprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/groupbytraceprocessor"
	intervalprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/intervalprocessor"
	k8sattributesprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/k8sattributesprocessor"
	metricsgenerationprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/metricsgenerationprocessor"
	metricstransformprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/metricstransformprocessor"
	probabilisticsamplerprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor"
	redactionprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/redactionprocessor"
	remotetapprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/remotetapprocessor"
	resourcedetectionprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/resourcedetectionprocessor"
	resourceprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/resourceprocessor"
	routingprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/routingprocessor"
	spanprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/spanprocessor"
	sumologicprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/sumologicprocessor"
	tailsamplingprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/tailsamplingprocessor"
	transformprocessor "github.com/jacktomcat/opentelemetry-collector-contrib/processor/transformprocessor"
	activedirectorydsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/activedirectorydsreceiver"
	aerospikereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/aerospikereceiver"
	apachereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/apachereceiver"
	apachesparkreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/apachesparkreceiver"
	awscloudwatchreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/awscloudwatchreceiver"
	awscontainerinsightreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/awscontainerinsightreceiver"
	awsecscontainermetricsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver"
	awsfirehosereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/awsfirehosereceiver"
	awsxrayreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/awsxrayreceiver"
	azureblobreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/azureblobreceiver"
	azureeventhubreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/azureeventhubreceiver"
	azuremonitorreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/azuremonitorreceiver"
	bigipreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/bigipreceiver"
	carbonreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/carbonreceiver"
	chronyreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/chronyreceiver"
	cloudflarereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/cloudflarereceiver"
	cloudfoundryreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/cloudfoundryreceiver"
	collectdreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/collectdreceiver"
	couchdbreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/couchdbreceiver"
	datadogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/datadogreceiver"
	dockerstatsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/dockerstatsreceiver"
	elasticsearchreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/elasticsearchreceiver"
	expvarreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/expvarreceiver"
	filelogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/filelogreceiver"
	filestatsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/filestatsreceiver"
	flinkmetricsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/flinkmetricsreceiver"
	fluentforwardreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/fluentforwardreceiver"
	googlecloudpubsubreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver"
	googlecloudspannerreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/googlecloudspannerreceiver"
	haproxyreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/haproxyreceiver"
	hostmetricsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/hostmetricsreceiver"
	httpcheckreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/httpcheckreceiver"
	iisreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/iisreceiver"
	influxdbreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/influxdbreceiver"
	jaegerreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/jaegerreceiver"
	jmxreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/jmxreceiver"
	journaldreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/journaldreceiver"
	k8sclusterreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/k8sclusterreceiver"
	k8seventsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/k8seventsreceiver"
	k8sobjectsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/k8sobjectsreceiver"
	kafkametricsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/kafkametricsreceiver"
	kafkareceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/kafkareceiver"
	kubeletstatsreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver"
	lokireceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/lokireceiver"
	memcachedreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/memcachedreceiver"
	mongodbatlasreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/mongodbatlasreceiver"
	mongodbreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/mongodbreceiver"
	mysqlreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/mysqlreceiver"
	namedpipereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/namedpipereceiver"
	nginxreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/nginxreceiver"
	nsxtreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/nsxtreceiver"
	opencensusreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/opencensusreceiver"
	oracledbreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/oracledbreceiver"
	otlpjsonfilereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver"
	podmanreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/podmanreceiver"
	postgresqlreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/postgresqlreceiver"
	prometheusreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/prometheusreceiver"
	pulsarreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/pulsarreceiver"
	purefareceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/purefareceiver"
	purefbreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/purefbreceiver"
	rabbitmqreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/rabbitmqreceiver"
	receivercreator "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/receivercreator"
	redisreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/redisreceiver"
	riakreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/riakreceiver"
	sapmreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/sapmreceiver"
	signalfxreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/signalfxreceiver"
	simpleprometheusreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/simpleprometheusreceiver"
	skywalkingreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/skywalkingreceiver"
	snmpreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/snmpreceiver"
	snowflakereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/snowflakereceiver"
	solacereceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/solacereceiver"
	splunkhecreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/splunkhecreceiver"
	sqlqueryreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/sqlqueryreceiver"
	sqlserverreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/sqlserverreceiver"
	sshcheckreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/sshcheckreceiver"
	statsdreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/statsdreceiver"
	syslogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/syslogreceiver"
	tcplogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/tcplogreceiver"
	udplogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/udplogreceiver"
	vcenterreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/vcenterreceiver"
	wavefrontreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/wavefrontreceiver"
	webhookeventreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/webhookeventreceiver"
	windowseventlogreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/windowseventlogreceiver"
	windowsperfcountersreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/windowsperfcountersreceiver"
	zipkinreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/zipkinreceiver"
	zookeeperreceiver "github.com/jacktomcat/opentelemetry-collector-contrib/receiver/zookeeperreceiver"
)

func components() (otelcol.Factories, error) {
	var err error
	factories := otelcol.Factories{}

	factories.Extensions, err = extension.MakeFactoryMap(
		zpagesextension.NewFactory(),
		ballastextension.NewFactory(),
		asapauthextension.NewFactory(),
		awsproxy.NewFactory(),
		basicauthextension.NewFactory(),
		bearertokenauthextension.NewFactory(),
		headerssetterextension.NewFactory(),
		healthcheckextension.NewFactory(),
		httpforwarderextension.NewFactory(),
		jaegerremotesampling.NewFactory(),
		oauth2clientauthextension.NewFactory(),
		ecsobserver.NewFactory(),
		ecstaskobserver.NewFactory(),
		hostobserver.NewFactory(),
		k8sobserver.NewFactory(),
		dockerobserver.NewFactory(),
		oidcauthextension.NewFactory(),
		opampextension.NewFactory(),
		pprofextension.NewFactory(),
		remotetapextension.NewFactory(),
		sigv4authextension.NewFactory(),
		solarwindsapmsettingsextension.NewFactory(),
		dbstorage.NewFactory(),
		filestorage.NewFactory(),
		sumologicextension.NewFactory(),
		otlpencodingextension.NewFactory(),
		jaegerencodingextension.NewFactory(),
		jsonlogencodingextension.NewFactory(),
		textencodingextension.NewFactory(),
		zipkinencodingextension.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}

	factories.Receivers, err = receiver.MakeFactoryMap(
		nopreceiver.NewFactory(),
		otlpreceiver.NewFactory(),
		activedirectorydsreceiver.NewFactory(),
		aerospikereceiver.NewFactory(),
		apachereceiver.NewFactory(),
		apachesparkreceiver.NewFactory(),
		awscloudwatchreceiver.NewFactory(),
		awscontainerinsightreceiver.NewFactory(),
		awsecscontainermetricsreceiver.NewFactory(),
		awsfirehosereceiver.NewFactory(),
		awsxrayreceiver.NewFactory(),
		azureblobreceiver.NewFactory(),
		azureeventhubreceiver.NewFactory(),
		azuremonitorreceiver.NewFactory(),
		bigipreceiver.NewFactory(),
		carbonreceiver.NewFactory(),
		chronyreceiver.NewFactory(),
		cloudflarereceiver.NewFactory(),
		cloudfoundryreceiver.NewFactory(),
		collectdreceiver.NewFactory(),
		couchdbreceiver.NewFactory(),
		datadogreceiver.NewFactory(),
		dockerstatsreceiver.NewFactory(),
		elasticsearchreceiver.NewFactory(),
		expvarreceiver.NewFactory(),
		filelogreceiver.NewFactory(),
		filestatsreceiver.NewFactory(),
		flinkmetricsreceiver.NewFactory(),
		fluentforwardreceiver.NewFactory(),
		googlecloudpubsubreceiver.NewFactory(),
		googlecloudspannerreceiver.NewFactory(),
		haproxyreceiver.NewFactory(),
		hostmetricsreceiver.NewFactory(),
		httpcheckreceiver.NewFactory(),
		influxdbreceiver.NewFactory(),
		iisreceiver.NewFactory(),
		jaegerreceiver.NewFactory(),
		jmxreceiver.NewFactory(),
		journaldreceiver.NewFactory(),
		k8sclusterreceiver.NewFactory(),
		k8seventsreceiver.NewFactory(),
		k8sobjectsreceiver.NewFactory(),
		kafkametricsreceiver.NewFactory(),
		kafkareceiver.NewFactory(),
		kubeletstatsreceiver.NewFactory(),
		lokireceiver.NewFactory(),
		memcachedreceiver.NewFactory(),
		mongodbatlasreceiver.NewFactory(),
		mongodbreceiver.NewFactory(),
		mysqlreceiver.NewFactory(),
		namedpipereceiver.NewFactory(),
		nginxreceiver.NewFactory(),
		nsxtreceiver.NewFactory(),
		opencensusreceiver.NewFactory(),
		oracledbreceiver.NewFactory(),
		otlpjsonfilereceiver.NewFactory(),
		podmanreceiver.NewFactory(),
		postgresqlreceiver.NewFactory(),
		prometheusreceiver.NewFactory(),
		pulsarreceiver.NewFactory(),
		purefareceiver.NewFactory(),
		purefbreceiver.NewFactory(),
		rabbitmqreceiver.NewFactory(),
		receivercreator.NewFactory(),
		redisreceiver.NewFactory(),
		riakreceiver.NewFactory(),
		sapmreceiver.NewFactory(),
		signalfxreceiver.NewFactory(),
		simpleprometheusreceiver.NewFactory(),
		skywalkingreceiver.NewFactory(),
		snowflakereceiver.NewFactory(),
		solacereceiver.NewFactory(),
		splunkhecreceiver.NewFactory(),
		sqlqueryreceiver.NewFactory(),
		sqlserverreceiver.NewFactory(),
		sshcheckreceiver.NewFactory(),
		statsdreceiver.NewFactory(),
		syslogreceiver.NewFactory(),
		tcplogreceiver.NewFactory(),
		udplogreceiver.NewFactory(),
		vcenterreceiver.NewFactory(),
		wavefrontreceiver.NewFactory(),
		webhookeventreceiver.NewFactory(),
		snmpreceiver.NewFactory(),
		windowsperfcountersreceiver.NewFactory(),
		windowseventlogreceiver.NewFactory(),
		zipkinreceiver.NewFactory(),
		zookeeperreceiver.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}

	factories.Exporters, err = exporter.MakeFactoryMap(
		debugexporter.NewFactory(),
		nopexporter.NewFactory(),
		otlpexporter.NewFactory(),
		otlphttpexporter.NewFactory(),
		alertmanagerexporter.NewFactory(),
		alibabacloudlogserviceexporter.NewFactory(),
		awscloudwatchlogsexporter.NewFactory(),
		awsemfexporter.NewFactory(),
		awskinesisexporter.NewFactory(),
		awss3exporter.NewFactory(),
		awsxrayexporter.NewFactory(),
		azuredataexplorerexporter.NewFactory(),
		azuremonitorexporter.NewFactory(),
		carbonexporter.NewFactory(),
		clickhouseexporter.NewFactory(),
		cassandraexporter.NewFactory(),
		coralogixexporter.NewFactory(),
		datadogexporter.NewFactory(),
		datasetexporter.NewFactory(),
		dynatraceexporter.NewFactory(),
		elasticsearchexporter.NewFactory(),
		fileexporter.NewFactory(),
		googlecloudexporter.NewFactory(),
		googlecloudpubsubexporter.NewFactory(),
		googlemanagedprometheusexporter.NewFactory(),
		honeycombmarkerexporter.NewFactory(),
		influxdbexporter.NewFactory(),
		instanaexporter.NewFactory(),
		kafkaexporter.NewFactory(),
		loadbalancingexporter.NewFactory(),
		logicmonitorexporter.NewFactory(),
		logzioexporter.NewFactory(),
		lokiexporter.NewFactory(),
		mezmoexporter.NewFactory(),
		opencensusexporter.NewFactory(),
		opensearchexporter.NewFactory(),
		prometheusexporter.NewFactory(),
		prometheusremotewriteexporter.NewFactory(),
		pulsarexporter.NewFactory(),
		sapmexporter.NewFactory(),
		sentryexporter.NewFactory(),
		signalfxexporter.NewFactory(),
		skywalkingexporter.NewFactory(),
		splunkhecexporter.NewFactory(),
		sumologicexporter.NewFactory(),
		syslogexporter.NewFactory(),
		tencentcloudlogserviceexporter.NewFactory(),
		zipkinexporter.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}

	factories.Processors, err = processor.MakeFactoryMap(
		batchprocessor.NewFactory(),
		memorylimiterprocessor.NewFactory(),
		attributesprocessor.NewFactory(),
		cumulativetodeltaprocessor.NewFactory(),
		deltatorateprocessor.NewFactory(),
		filterprocessor.NewFactory(),
		groupbyattrsprocessor.NewFactory(),
		groupbytraceprocessor.NewFactory(),
		intervalprocessor.NewFactory(),
		k8sattributesprocessor.NewFactory(),
		metricsgenerationprocessor.NewFactory(),
		metricstransformprocessor.NewFactory(),
		probabilisticsamplerprocessor.NewFactory(),
		redactionprocessor.NewFactory(),
		resourcedetectionprocessor.NewFactory(),
		resourceprocessor.NewFactory(),
		routingprocessor.NewFactory(),
		sumologicprocessor.NewFactory(),
		spanprocessor.NewFactory(),
		tailsamplingprocessor.NewFactory(),
		transformprocessor.NewFactory(),
		remotetapprocessor.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}

	factories.Connectors, err = connector.MakeFactoryMap(
		forwardconnector.NewFactory(),
		countconnector.NewFactory(),
		datadogconnector.NewFactory(),
		exceptionsconnector.NewFactory(),
		grafanacloudconnector.NewFactory(),
		routingconnector.NewFactory(),
		servicegraphconnector.NewFactory(),
		spanmetricsconnector.NewFactory(),
	)
	if err != nil {
		return otelcol.Factories{}, err
	}

	return factories, nil
}
